[package]
name = "coap-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.80"
reqwest = "0.11.24"
bytes = "1.5.0"
url = "2.5.0"
http = "1.0.0"
coap = "0.14.3"
coap-lite = "0.11.5"
tokio = {version = "^1.36", features = ["full"]}
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
